# -*- coding: utf-8 -*-
"""Eksperimen_SML_Rivaldo.ipynb

Automatically generated by Colab.

Original file is located at
  https://colab.research.google.com/drive/1PYFv-n7DHIMD9BMme0BEZlSkES_ilBSL#scrollTo=roKOZbAGNR2I  

"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
import os

def automate_preprocessing(input_path, output_path):
    print("🚀 Memulai proses preprocessing otomatis untuk IEA Global EV Data 2024...\n")

    # 1. Load dataset
    df = pd.read_csv(input_path)
    print(f"✅ Dataset berhasil dimuat: {df.shape[0]} baris, {df.shape[1]} kolom")

    # 2. Normalisasi nama kolom
    df.columns = df.columns.str.strip().str.lower().str.replace(r'[\s\.]+', '_', regex=True)

    # 3. Menangani missing values
    missing = df.isnull().sum().sum()
    if missing > 0:
        print(f"⚠️ Ditemukan {missing} nilai kosong, akan dihapus...")
        df.dropna(inplace=True)
    else:
        print("✅ Tidak ada missing values")

    # 4. Hapus duplikasi
    dup = df.duplicated().sum()
    if dup > 0:
        print(f"⚠️ Ditemukan {dup} baris duplikat, akan dihapus...")
        df.drop_duplicates(inplace=True)
    else:
        print("✅ Tidak ada data duplikat")

    # 5. Standarisasi kolom numerik
    scaler = StandardScaler()
    if 'value' in df.columns:
        df['value_scaled'] = scaler.fit_transform(df[['value']])
        print("✅ Kolom numerik 'value' berhasil distandarisasi")

    # 6. Encoding kolom kategorikal
    encoder = LabelEncoder()
    cat_cols = ['region', 'category', 'parameter', 'mode', 'powertrain', 'unit']
    for col in cat_cols:
        if col in df.columns:
            df[col] = encoder.fit_transform(df[col])
    print("✅ Kolom kategorikal berhasil di-encode")

    # 7. Simpan hasil preprocessing
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df.to_csv(output_path, index=False)
    print(f"\n💾 File hasil preprocessing disimpan di: {output_path}")
    print(f"📊 Ukuran akhir dataset: {df.shape[0]} baris, {df.shape[1]} kolom")

if __name__ == "__main__":
    automate_preprocessing(
        input_path='IEA_Global_EV_Data_2024.csv',
        output_path='preprocessed/IEA_Global_EV_Data_2024_cleaned.csv'
    )
